[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[scheduled-functions]]
  function = "keep-alive"
  schedule = "0 10 */4 * *"
